version: "3"
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/public
    php:
        build:
            ./docker/php/
        expose:
            - 9000
        volumes:
            - .:/var/www/public
    mysql:
        image: mariadb:latest
        expose:
            - 3306
        volumes:
            - .:/var/www/public
        env_file:
            - ./docker/mariasql/mariasql.env
