version: '2'

volumes:
    database_data:
        driver: local
services:
    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - .:/var/www/public
    database:
        image: mariadb:latest
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: find
            MYSQL_USER: project
            MYSQL_PASSWORD: project